/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.av2maven;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Conexao;
import static models.Conexao.Conectar;
import static models.Conexao.Desconectar;

/**
 *
 * @author pedro
 * Esta é a classe de formulario que realiza emprestimos
 */
public class FormularioRealizarEmprestimos extends javax.swing.JFrame  {

    ArrayList<Integer> j = new ArrayList();


    /**
     * Creates new form FormularioRealizarEmprestimos
     */
    public FormularioRealizarEmprestimos() {
        j.add(1); j.add(2); j.add(3); j.add(4); j.add(5); j.add(6); j.add(7);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLDevolucao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLDataAtual = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBConfirmarEmprestimo = new javax.swing.JButton();
        jComboBoxMembros = new javax.swing.JComboBox();
        jComboBoxLivros = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTDiassss = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(205, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Selecione o membro requirente:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Realizar Emprestimo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data de devolução:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selecione o Livro que será emprestado:");

        jLDevolucao.setFont(new java.awt.Font("Tahoma", 1, 14));
        Date dataTeste = new Date();

        Calendar cal = Calendar.getInstance();
        cal.setTime(dataTeste );
        cal.add(Calendar.DATE, Conexao.diasEmprestimo.get(0));
        dataTeste = cal.getTime();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = dateFormat.format(dataTeste);
        jLDevolucao.setText(strDate);
        jLDevolucao.setDoubleBuffered(true);
        jLDevolucao.setOpaque(true);
        jLDevolucao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLDevolucaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Data atual:");

        jLDataAtual.setFont(new java.awt.Font("Tahoma", 1, 14));
        //Date d = new Date();
        //Long data = d.getTime();
        //String date = Long.toString(data);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jLDataAtual.setText(sdf.format(new Date()));

        jButton1.setText("Voltar");
        jButton1.setPreferredSize(new java.awt.Dimension(137, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBConfirmarEmprestimo.setText("Confirmar Emprestimo");
        jBConfirmarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarEmprestimoActionPerformed(evt);
            }
        });

        DefaultComboBoxModel t= new DefaultComboBoxModel();
        for (int i = 0; i < Conexao.membros.size(); i++) {
            t.addElement(Conexao.membros.get(i).getNome());
        }
        jComboBoxMembros.setModel(t/*new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" })*/);
        jComboBoxMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMembrosActionPerformed(evt);
            }
        });

        DefaultComboBoxModel w= new DefaultComboBoxModel();
        for (int i = 0; i < Conexao.livros.size(); i++) {
            w.addElement(Conexao.livros.get(i).getTitulo());
        }
        jComboBoxLivros.setModel(w/*new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" })*/);
        jComboBoxLivros.setAutoscrolls(true);
        jComboBoxLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLivrosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Defina primeiro os dias do emprestimo (ex: 7) : ");

        jButton2.setText("Alterar dia de Devolução");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(288, 288, 288))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBConfirmarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTDiassss, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton2)
                    .addComponent(jTDiassss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLDataAtual)
                    .addComponent(jLDevolucao)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jBConfirmarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBConfirmarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarEmprestimoActionPerformed
    //Pega os ids certos
        String membro = (String) jComboBoxMembros.getSelectedItem();
    String livro = (String) jComboBoxLivros.getSelectedItem();
    
    
    //pegar os dados  para popular a tabela emprestimos
    int id_usuario = 0;
    int id_livro = 0;
    String dataPedido = jLDataAtual.getText();
    String dataDevolucao = jLDevolucao.getText();
    //
    
    for(int i = 0 ; i < Conexao.emprestimosAtrasados.size(); i++){
        
        if(Conexao.emprestimosAtrasados.get(i).getId_usuario().equals(membro)){
            JOptionPane.showMessageDialog(null, "ERRO: Membro Devedor.\nNão poderá pegar outro livro até devolver o pendente");
            this.dispose();
            return;
        
        
    }
    
    }
    
    
    for(int i = 0 ; i < Conexao.membros.size(); i++){
        
        if(Conexao.membros.get(i).getNome().equals(membro)){
            id_usuario = Conexao.membros.get(i).getId();
        }
        
    }
    
    for(int i = 0 ; i < Conexao.livros.size(); i++){
        if(Conexao.livros.get(i).getTitulo().equals(livro)){
            id_livro = Conexao.livros.get(i).getId();
        }
    }
    
    
    String INSERIR  = "INSERT INTO Emprestimos (id_usuario, id_livro, data_pedido, data_devolucao) VALUES (?,?,?,?) ";
    
    try{
        Connection conn = Conectar();
        PreparedStatement emprestimoStatement = conn.prepareStatement(INSERIR);
              
              emprestimoStatement.setInt(1, id_usuario);
              emprestimoStatement.setInt(2, id_livro);        
              emprestimoStatement.setString(3, dataPedido);        
              emprestimoStatement.setString(4, dataDevolucao);       
              
              int res = emprestimoStatement.executeUpdate();
              
              
              if(res > 0){
                  JOptionPane.showMessageDialog(null, "Emprestimo cadastrado com Sucesso!");
                  Conexao.importarEmprestimos();
              }else{
                  JOptionPane.showMessageDialog(null, "Erro ao Cadastrar o Emprestimo. Contacte o Administrador do Sistema");
              }
              this.dispose();
              emprestimoStatement.close();
              Conexao.Desconectar(conn);
              
              
    }catch(SQLException e){
        e.printStackTrace();
        System.err.println("Erro Inserir Dados emprestimoTable");
    }
     //Conexao.importarEmprestimos();
        Conexao.emprestimos.clear();
        Conexao.importarEmprestimos();
    /* for(int i = 0 ;i < Conexao.emprestimos.size(); i++){
         
         if(Conexao.livros.get(i).getTitulo().equals(Conexao.emprestimos.get(i).getId_livro())){
             
             String Livro = Conexao.livros.get(i).getTitulo();
             String situacao  =  Conexao.situacao[1];
             
             Conexao.mudarSituacao(situacao, Livro);
            
         
         }}*/
     
     
    
// TODO add your handling code here:
    }//GEN-LAST:event_jBConfirmarEmprestimoActionPerformed

    private void jComboBoxMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMembrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMembrosActionPerformed

    private void jComboBoxLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLivrosActionPerformed

    private void jLDevolucaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLDevolucaoAncestorAdded
       
        
     
        
        
        /*jLDevolucao.repaint();
        jLDevolucao.updateUI();
        int diasAlugado =  (int) jComboBoxDiasAlugado.getSelectedIndex();    
        GregorianCalendar vencimento = new GregorianCalendar(); 
		 vencimento.setTime(new Date());
		 this.repaint();
		 vencimento.add(Calendar.DAY_OF_MONTH, diasAlugado);  		
		 this.repaint();
SimpleDateFormat fmt = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    fmt.setCalendar(vencimento);
    String dateFormatted = fmt.format(vencimento.getTime());
    jLDevolucao.setText(dateFormatted);
    jLDevolucao.repaint();// TODO add your handling code here:
    jLDevolucao.updateUI();*/
    }//GEN-LAST:event_jLDevolucaoAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int diasAlugado =  Integer.parseInt(jTDiassss.getText());
     /// se tava adicionando dados na tabela em vez de fazer o update manu, então amanha se ve na udemy o carinha fazendo o update e pa funfa :'3 bjus'
      String ATUALIZAR = "UPDATE DiasEmprestimo SET dias = ? WHERE id = 1";
            try{
           Connection conn = Conectar();
            PreparedStatement inserirStatement = conn.prepareStatement(ATUALIZAR);          
            
            inserirStatement.setInt(1, diasAlugado);
            
                      int res = inserirStatement.executeUpdate();
                      if(res > 0){
                          JOptionPane.showMessageDialog(null, "Dia de devolução alterado com sucesso!");
                          this.dispose();
                          //this.setVisible(true);
                            Conexao.diasEmprestimo.clear();
                            Conexao.importarDiasEmprestimo();
                            jPanel1.repaint();
                            //jLDevolucao.setText();


                          FormularioRealizarEmprestimos a = new FormularioRealizarEmprestimos();
                           a.setVisible(true);
                           
                          
                          
                      }
            
                inserirStatement.close();
                Conexao.Desconectar(conn);
            }catch(HeadlessException e){
                 JOptionPane.showMessageDialog(null, "Erro ao cadastrar Membro\nContacte o administrador do Sistema.");
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar Membro\nContacte o administrador do Sistema.");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioRealizarEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioRealizarEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioRealizarEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioRealizarEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioRealizarEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmarEmprestimo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxLivros;
    private javax.swing.JComboBox<String> jComboBoxMembros;
    private javax.swing.JLabel jLDataAtual;
    private javax.swing.JLabel jLDevolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTDiassss;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
