/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.av2maven;

import com.mycompany.av2maven.FormularioCadastroUser;
import static java.lang.System.exit;
import models.Conexao;
import models.TableModelDevedores;
import models.TableModelDevolucoes;
import models.TableModelEmprestimos1;
import models.TableModelEmprestimos2;
import models.TableModelLivros;
import models.TableModelMembros;

/**
 *
 * @author pedro
 * Tela Principal do sistema.
 * Seta a estrutura das tabelas e interfaces
 */
public class UserAdmTela extends javax.swing.JFrame {

    /**
     * Creates new form UserAdmTela
     * 
     * Seta a estrutura das tabelas e interfaces
     *
     */
    
    TableModelLivros tablemodel = new TableModelLivros();
    TableModelMembros tablemodel2 = new TableModelMembros();
    TableModelEmprestimos1 tablemodel3 = new TableModelEmprestimos1();
    TableModelEmprestimos2 tablemodel4 = new TableModelEmprestimos2();
    TableModelDevolucoes tablemodel5 = new TableModelDevolucoes();
    TableModelDevedores tablemodel6 = new TableModelDevedores();
    public UserAdmTela() {
        initComponents();
        
        jTLivros.setModel(tablemodel);
        
        jTLivros.getColumnModel().getColumn(0).setPreferredWidth(50); 
        jTLivros.getColumnModel().getColumn(1).setPreferredWidth(670); 
        jTLivros.getColumnModel().getColumn(2).setPreferredWidth(200);
        
        
        //membros
        jTMembros.setModel(tablemodel2);
        
        jTMembros.getColumnModel().getColumn(0).setPreferredWidth(40); 
        jTMembros.getColumnModel().getColumn(1).setPreferredWidth(200); 
        jTMembros.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTMembros.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTMembros.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTMembros.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTMembros.getColumnModel().getColumn(7).setPreferredWidth(200);
        
        //emprestimos1
        jTEmprestimos1.setModel(tablemodel3);
        
        jTEmprestimos1.getColumnModel().getColumn(0).setPreferredWidth(40); 
        jTEmprestimos1.getColumnModel().getColumn(1).setPreferredWidth(200); 
        jTEmprestimos1.getColumnModel().getColumn(2).setPreferredWidth(670);
        jTEmprestimos1.getColumnModel().getColumn(3).setPreferredWidth(350);
        jTEmprestimos1.getColumnModel().getColumn(4).setPreferredWidth(200);
        
        //emprstimos2
        jTEmprestimos2.setModel(tablemodel4);
        
        jTEmprestimos2.getColumnModel().getColumn(0).setPreferredWidth(40); 
        jTEmprestimos2.getColumnModel().getColumn(1).setPreferredWidth(200); 
        jTEmprestimos2.getColumnModel().getColumn(2).setPreferredWidth(670);
        jTEmprestimos2.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTEmprestimos2.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTEmprestimos2.getColumnModel().getColumn(5).setPreferredWidth(200);
        
        //devolucoes
        jTDevolucoes.setModel(tablemodel5);
        
        jTDevolucoes.getColumnModel().getColumn(0).setPreferredWidth(40); 
        jTDevolucoes.getColumnModel().getColumn(1).setPreferredWidth(200); 
        jTDevolucoes.getColumnModel().getColumn(2).setPreferredWidth(670);
        jTDevolucoes.getColumnModel().getColumn(3).setPreferredWidth(200);
        
        //devedores
        jTListDevedores.setModel(tablemodel6);
        
        jTListDevedores.getColumnModel().getColumn(0).setPreferredWidth(40); 
        jTListDevedores.getColumnModel().getColumn(1).setPreferredWidth(200); 
        jTListDevedores.getColumnModel().getColumn(2).setPreferredWidth(670);
        jTListDevedores.getColumnModel().getColumn(3).setPreferredWidth(300);
        jTListDevedores.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTListDevedores.getColumnModel().getColumn(5).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label_tab_Livros = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTLivros = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTEmprestimos1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTEmprestimos2 = new javax.swing.JTable();
        label_tab_Emprestimos1 = new javax.swing.JLabel();
        label_tab_Emprestimos2 = new javax.swing.JLabel();
        button_Registrar_Emprestimo = new javax.swing.JButton();
        button_Registrar_Devolução = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDevolucoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTListDevedores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_Cadastrar_Membro = new javax.swing.JButton();
        button_Remover_Membro = new javax.swing.JButton();
        label_tab_Membros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMembros = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema: Biblioteca");
        setLocation(new java.awt.Point(205, 100));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(153, 0, 153));
        jTabbedPane1.setDoubleBuffered(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Cadastrar Livro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover Livro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        label_tab_Livros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_tab_Livros.setText("Livros Cadastrados no sistema:");

        jTLivros.setBorder(new javax.swing.border.MatteBorder(null));
        jTLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTLivros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTLivros.setDoubleBuffered(true);
        jTLivros.setFillsViewportHeight(true);
        jTLivros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTLivros.setShowGrid(true);
        jTLivros.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTLivros);
        if (jTLivros.getColumnModel().getColumnCount() > 0) {
            jTLivros.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTLivros.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTLivros.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTLivros.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(413, 413, 413))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tab_Livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(202, 202, 202)
                .addComponent(jButton2)
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addGap(203, 203, 203))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(label_tab_Livros, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Livros", jPanel1);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jTEmprestimos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEmprestimos1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTEmprestimos1.setFillsViewportHeight(true);
        jTEmprestimos1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTEmprestimos1);

        jTEmprestimos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEmprestimos2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTEmprestimos2.setFillsViewportHeight(true);
        jTEmprestimos2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTEmprestimos2);

        label_tab_Emprestimos1.setBackground(new java.awt.Color(246, 71, 71));
        label_tab_Emprestimos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_tab_Emprestimos1.setText("Emprestimos em curso:");

        label_tab_Emprestimos2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_tab_Emprestimos2.setText("Emprestimos em atraso:");

        button_Registrar_Emprestimo.setText("Registrar Emprestimo");
        button_Registrar_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Registrar_EmprestimoActionPerformed(evt);
            }
        });

        button_Registrar_Devolução.setText("Registrar Devolução");
        button_Registrar_Devolução.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Registrar_DevoluçãoActionPerformed(evt);
            }
        });

        jButton5.setText("Atualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(button_Registrar_Emprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(button_Registrar_Devolução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(211, 211, 211))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tab_Emprestimos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tab_Emprestimos2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tab_Emprestimos1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(label_tab_Emprestimos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Registrar_Devolução, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Registrar_Emprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Emprestimos", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jTDevolucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTDevolucoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTDevolucoes.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTDevolucoes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Devoluções:");

        jTListDevedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTListDevedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTListDevedores.setFillsViewportHeight(true);
        jScrollPane6.setViewportView(jTListDevedores);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Lista de Devedores:");

        jButton6.setText("Atualizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registros", jPanel5);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        button_Cadastrar_Membro.setText("Cadastrar Membro");
        button_Cadastrar_Membro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Cadastrar_MembroActionPerformed(evt);
            }
        });

        button_Remover_Membro.setText("Remover Membro");
        button_Remover_Membro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Remover_MembroActionPerformed(evt);
            }
        });

        label_tab_Membros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_tab_Membros.setText("Membros cadastrados no sistema:");

        jTMembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTMembros.setToolTipText("");
        jTMembros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTMembros.setDoubleBuffered(true);
        jTMembros.setFillsViewportHeight(true);
        jTMembros.setShowGrid(true);
        jTMembros.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTMembros);
        if (jTMembros.getColumnModel().getColumnCount() > 0) {
            jTMembros.getColumnModel().getColumn(3).setPreferredWidth(500);
        }

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(button_Cadastrar_Membro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(button_Remover_Membro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_tab_Membros, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tab_Membros)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Cadastrar_Membro)
                    .addComponent(button_Remover_Membro))
                .addGap(32, 32, 32))
        );

        button_Cadastrar_Membro.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Membros", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jButton7.setText("Deslogar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("Sobre");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Informações");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(237, 237, 237))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGap(235, 235, 235)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(74, 74, 74))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addGap(309, 309, 309)))
        );

        jTabbedPane1.addTab("Sobre", jPanel3);

        jMenu1.setText("Menu");

        jMenuItem2.setText("Deslogar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configurações");

        jMenu3.setText("Administrador");

        jMenuItem4.setText("Adicionar Administrador");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Remover Administrador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    FormularioCadastroLivro a = new FormularioCadastroLivro();
    a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button_Cadastrar_MembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Cadastrar_MembroActionPerformed
     FormularioCadastroUser a = new FormularioCadastroUser();
     a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_button_Cadastrar_MembroActionPerformed

    private void button_Registrar_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Registrar_EmprestimoActionPerformed
       Conexao.importarDiasEmprestimo();
        FormularioRealizarEmprestimos a = new FormularioRealizarEmprestimos();
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_button_Registrar_EmprestimoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    FormularioRemoverLivro a = new FormularioRemoverLivro();
    a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Conexao.livros.clear();
        Conexao.ImportarLivros();
        
        tablemodel.fireTableDataChanged();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button_Remover_MembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Remover_MembroActionPerformed
            FormularioRemoverMembros a = new FormularioRemoverMembros();
            a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_button_Remover_MembroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Conexao.membros.clear();
        Conexao.ImportarMembros();
        
        tablemodel2.fireTableDataChanged(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        TelaInicial a = new TelaInicial();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         Conexao.emprestimos.clear();
        Conexao.importarEmprestimos();
        tablemodel3.fireTableDataChanged();
       
        Conexao.emprestimosAtrasados.clear();
        Conexao.ImportarANDSetarEmprestimosAtrasados();
        tablemodel4.fireTableDataChanged(); 
       
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     this.dispose();
        TelaInicial a = new TelaInicial();
        a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void button_Registrar_DevoluçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Registrar_DevoluçãoActionPerformed
              FormularioDarBaixaEmprestimo a = new FormularioDarBaixaEmprestimo();
              a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_button_Registrar_DevoluçãoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    Conexao.devolucoes.clear();
    Conexao.ImportarDevolucoes();
    Conexao.listaDevedores.clear();
    Conexao.ImportarDevedores();
    
     tablemodel5.fireTableDataChanged(); 
     tablemodel6.fireTableDataChanged();
    
    
    
    
            
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FormularioAddAdm a = new FormularioAddAdm();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       FormularioRemoverAdm a = new FormularioRemoverAdm();
       a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    InformacoesSistema a = new InformacoesSistema();
    a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    Sobre a = new Sobre();
    a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAdmTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cadastrar_Membro;
    private javax.swing.JButton button_Registrar_Devolução;
    private javax.swing.JButton button_Registrar_Emprestimo;
    private javax.swing.JButton button_Remover_Membro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTDevolucoes;
    private javax.swing.JTable jTEmprestimos1;
    private javax.swing.JTable jTEmprestimos2;
    private javax.swing.JTable jTListDevedores;
    private javax.swing.JTable jTLivros;
    private javax.swing.JTable jTMembros;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_tab_Emprestimos1;
    private javax.swing.JLabel label_tab_Emprestimos2;
    private javax.swing.JLabel label_tab_Livros;
    private javax.swing.JLabel label_tab_Membros;
    // End of variables declaration//GEN-END:variables
}
